### ISSUE TITLE
Console warnings/errors

### ISSUE THREAD

**Issue by wildpow** [babichjacob/sapper-postcss-template#12]
<img width="802" alt="Screen Shot 2020-05-07 at 4 23 30 PM" src="https://user-images.githubusercontent.com/17464319/81353893-1f623e80-907f-11ea-9fe2-73bda8755a16.png">

Not sure how to handle the `segment` one but, the other two are from the manifest still pointing at `logo-192.png`. I would just change the manifest to point to the favicon but, I wanted to get your opinion. Didn't know if you had a custom image that you wanted to use or not.

**Comment by babichjacob** [comment]
The `segment` warning was worked around in 9d1fe76.

I stopped putting off learning about `manifest.json` to solve the second error, so hopefully what I learned in ~30 minutes is actually good. That and other changes (like getting as high of a Lighthouse score as is within our control and iOS home screen icons) are in 47ad0cb6f6b65b8d5f3311fb2d8802fe394cd657.

By the way, the included 🌐 icon used in all the images is from [Mozilla's FOSS emoji set](https://mozilla.github.io/fxemoji/dist/FirefoxEmoji/index.html). It's been resized to fit within a circle 80% the size of the canvas, because this is the [entire maskable area available](https://web.dev/maskable-icon/). Because people using this template are obviously expected to replace these images with their own, we should probably inform them of this in a "Configuration" section in the README. (This is mostly a note to self that doesn't require response).
