### ISSUE TITLE
Cannot resolve package exports target '[object Object]'

### ISSUE THREAD

**Issue by hmaesta** [babichjacob/sapper-postcss-template#26]
Hello, Jacob.
By far this is the best documented Sapper + Tailwind CSS template – and the only one already shipping with Tailwind CSS 2.0.
So... Thank you for encouraging Svelte environment :) 

I cloned this repo and installed packages with `yarn install` just fine, but when running `yarn dev` I get the following error:

![Screen Shot 2020-12-08 at 19 23 35](https://user-images.githubusercontent.com/741969/101553715-fcd93080-3993-11eb-83cb-d12f1b12776e.png)

`localhost:3000` works, but without any CSS.

(Node: v12.14.1)

**Comment by babichjacob** [comment]
Can you try Node 14.15?

Either way, I can try testing this on my own... in the future. (I'm busy with university.)

**Comment by hmaesta** [comment]
That was it! Switched to v14.15.1 and it's working as expected. 🎉
Maybe this info should be added to repo README?

Thank you for your help.

**Comment by hmaesta** [comment]
_Taking advance of the already open issue..._ 

With `yarn build` the `global.css` has 12 KB, but with `yarn export` it has 4,8 MB. Any clues of what may be happening?

The `purge` part of `tailwind.config.js` is untouched.

**Comment by babichjacob** [comment]
> That was it! Switched to v14.15.1 and it's working as expected. 🎉
> Maybe this info should be added to repo README?
> 
> Thank you for your help.

No problem. I've updated the minimum Node version in the README from 12 to 14.15.

**Comment by babichjacob** [comment]
> _Taking advance of the already open issue..._
> 
> With `yarn build` the `global.css` has 12 KB, but with `yarn export` it has 4,8 MB. Any clues of what may be happening?
> 
> The `purge` part of `tailwind.config.js` is untouched.

I can't reproduce this.
The `export` command was already set up to enable purge because of the `NODE_ENV=production` environment variable setting in the build script.

I would worry about a race condition between Sapper's export copying static files sooner than `build-global-css` creates `global.css`, possibly leading to the `global.css` that was created during `dev` being used instead. 
So to figure out whether or not that's happening, try to `rm static/global.css` right before `yarn export`. If there ends up being no `global.css` file, there was a race condition (that I don't currently know how to fix); if there's an unpurged / unminified `global.css` file, then there must be a different problem.

(Check both `static/global.css` and `__sapper__/export/global.css`, please)

If you use [CI/CD for building / pushing your site](https://github.com/babichjacob/sapper-firebase-typescript-graphql-tailwindcss-actions-template/blob/main/.github/workflows/build-and-deploy.yml), knowing whether or not it happens there too would be helpful.

**Comment by hmaesta** [comment]
Deleting `static/global.css` right before `yarn export` worked 🙌 

Since my project is really simple – and I will probably deploy it manually –, that's not a problem at all. I can manage to delete global.css from static dir when needed.

Thank you for your help, Jacob.
