### ISSUE TITLE
Why change from Tailwind's purge?

### ISSUE THREAD

**Issue by wildpow** [babichjacob/sapper-postcss-template#7]
Why did you change from Tailwind's built-in purge to doing it in the postCSS config in this [commit](https://github.com/wildpow/sapper-postcss-template/commit/f0d65d39a3dd10904e63fcf6c3edfd9c25781b48)?

**Comment by wildpow** [comment]
Did have a positive effect on export. 👍 
### Before
<img src="https://user-images.githubusercontent.com/17464319/81040360-0def1b80-8e60-11ea-801c-fd7940809565.png" width="250"/>

### After
<img src="https://user-images.githubusercontent.com/17464319/81040371-1182a280-8e60-11ea-941c-66f35dd07232.png" width="250"/>

**Comment by babichjacob** [comment]
If Tailwind is removed, it is no longer necessary to re-create the purge in `postcss.config.js`, so the `README` section about this doesn't need to have that code block in it anymore, and it won't be possible to make a mistake moving purging from Tailwind to PostCSS because that isn't needed anymore.

[The documentation](https://tailwindcss.com/docs/controlling-file-size/#purgecss-options) doesn't make it clear if you are able to override the default extractor, so I actually never tried this.

The only reason I can think of that the export got smaller may be because unused (hopefully) base styles are being purged now. [Tailwind's purge mode defaults to `conservative`](https://github.com/tailwindcss/tailwindcss/pull/1639#issue-409834686) which prevents base styles and user-created styles from being purged. On the other hand, I'm not sure that would account for a ~20 KB difference, but this is still good news!

**Comment by wildpow** [comment]
I am planning on moving an existing project to this config tonight or tomorrow. I'll let you know if I come crossed anything weird.

**Comment by wildpow** [comment]
I believe this question was answered, thank you.

**Comment by babichjacob** [comment]
Forgot to point out we use Tailwind's purge again since 6b596196a8b052e1a65ca59bc2b8fcad61e10e8d because it's been improved since I decided to ditch it, and I realized that if you're not using Tailwind you probably don't need or want PurgeCSS anyway.
